Added checkbox, now using global constants
Metatavu/meta-proj-cli pull request #104
Opened 2021-02-24 09:47 UTC by veikkahonkanen

Resolves #103

2021-02-24 12:20 UTC, eetupur approved these changes

2021-02-25 08:02 UTC, eetupur approved these changes

2021-02-25 08:13 UTC, jarinykanen requested changes

2021-02-25 08:13 UTC, jarinykanen commented on src/commands/checkTest.ts
> +                  { name: Software.Kustomize, checked: true} ];
```suggestion
const choices = [
  { name: Software.NodeJs, checked: true },
  { name: Software.GitHub, checked: true },
  { name: Software.GitCLI, checked: true },
  { name: Software.Maven, checked: true }, 
  { name: Software.JDK8, checked: true },
  { name: Software.JDK11, checked: false },
  { name: Software.Homebrew, checked: true },
  { name: Software.Docker, checked: true },
  { name: Software.Minikube, checked: true },
  { name: Software.KubernetesCLI, checked: true },
  { name: Software.Kustomize, checked: true }
];
```

2021-02-25 08:13 UTC, jarinykanen commented on src/commands/checkTest.ts
> +    });
```suggestion
  try {
    const tests: CheckSet[] = [];
    const checkBoxResult = await this.prompt({
      type: "checkbox",
      name: "software",
      choices: choices,
      message: "Check if installed: "
    });
```

2021-02-25 08:13 UTC, jarinykanen commented on src/commands/checkTest.ts
> +        tests.push({checkable : checkBoxResult.software[i], details : {}})
```suggestion
        tests.push({ checkable: checkBoxResult.software[i], details: { } })
```

2021-02-25 08:33 UTC, eetupur approved these changes

2021-02-25 11:28 UTC, jarinykanen approved these changes

2021-02-25 11:28 UTC, merged