Now properly handling checks
Metatavu/meta-proj-cli pull request #106
Opened 2021-02-24 12:45 UTC by veikkahonkanen

Resolves #105

2021-02-24 12:53 UTC, eetupur approved these changes

2021-02-25 11:42 UTC, eetupur approved these changes

2021-02-25 11:56 UTC, jarinykanen requested changes

2021-02-25 11:56 UTC, jarinykanen commented on src/classes/check-utils.ts
> +    const erroList : CheckErrorSet[] = [];
```suggestion
    const erroList: CheckErrorSet[] = [];
```

2021-02-25 11:56 UTC, jarinykanen commented on src/classes/check-utils.ts
> +        const checkResult : CheckErrorSet = await checkHandler(currentCheck);
```suggestion
        const checkResult: CheckErrorSet = await checkHandler(currentCheck);
```

2021-02-25 11:56 UTC, jarinykanen commented on src/classes/check-utils.ts
> +      details : installed ? null : `${currentCheck.checkable} not installed!`
```suggestion
      check: currentCheck.checkable,
      error: installed ? false : true,
      details: installed ? null : `${currentCheck.checkable} not installed!`
```

2021-03-03 06:45 UTC, jarinykanen requested changes

2021-03-03 06:45 UTC, jarinykanen commented on src/classes/check-utils.ts
> +const checkHandler = async (currentCheck: CheckSet) => {
Add return type to this function

2021-03-03 07:06 UTC, veikkahonkanen commented on src/classes/check-utils.ts
> +const checkHandler = async (currentCheck: CheckSet) => {
Added return type

2021-03-03 07:24 UTC, merged