Added eksctl and aws cli, enabled install wizard
Metatavu/meta-proj-cli pull request #110
Opened 2021-02-26 11:34 UTC by veikkahonkanen

Resolves #109

2021-02-26 12:10 UTC, eetupur approved these changes

2021-03-03 07:23 UTC, jarinykanen requested changes

2021-03-03 07:23 UTC, jarinykanen commented on src/commands/install.ts
> +];
These can be removed (check next comment)

2021-03-03 07:23 UTC, jarinykanen commented on src/commands/install.ts
> +        choices: choices,
```suggestion
       choices: Object.keys(Software),
```

2021-03-03 07:23 UTC, jarinykanen commented on src/commands/install.ts
>          name: 'software',
```suggestion
        type: "list",
        name: "software",
```

2021-03-03 07:23 UTC, jarinykanen commented on src/commands/install.ts
> +    }
Replace with switch case

2021-03-03 07:35 UTC, veikkahonkanen commented on src/commands/install.ts
> +    }
Replaced with switch case

2021-03-03 07:40 UTC, eetupur approved these changes

2021-03-04 06:21 UTC, jarinykanen approved these changes

2021-03-04 06:21 UTC, merged