attempted externalizaation of prompts
Metatavu/meta-proj-cli pull request #131
Opened 2021-03-11 12:52 UTC by eetupur

Resolves: #123.

2021-03-11 12:53 UTC, veikkahonkanen commented on package.json
> +    "@types/inquirer": "^7.3.1",
```suggestion
```

What kind of denedency is "i"?

2021-03-11 12:54 UTC, veikkahonkanen commented on src/classes/prompt-utils.ts
> +      const prompt = await inquirer.prompt({
```suggestion
  static inputPrompt = async (instance: any, message : string) : Promise<string | null> => {
    try {
      console.log(3);
      const prompt = await instance.prompt({
```

2021-03-11 12:54 UTC, veikkahonkanen commented on src/classes/prompt-utils.ts
> +      const prompt = await inquirer.prompt({
```suggestion
  static confirmPrompt = async (instance: any, message : string): Promise<string | null> => {
    try {
      const prompt = await instance.prompt({
```

2021-03-11 12:55 UTC, veikkahonkanen commented on src/classes/prompt-utils.ts
> +      const prompt = await inquirer.prompt({
```suggestion
  static listPrompt = async (instance: any, message : string, choices : string[]): Promise<string | null> => {
    try {
      const prompt = await instance.prompt({
```

2021-03-11 12:55 UTC, veikkahonkanen commented on src/commands/new-repo.ts
> +        const nameResult = await PromptUtils.inputPrompt("Give a name for the repository (leave empty to cancel): ");
```suggestion
        const nameResult = await PromptUtils.inputPrompt(this, "Give a name for the repository (leave empty to cancel): ");
```

2021-03-11 12:56 UTC, veikkahonkanen commented on src/commands/new-repo.ts
> +      const publicityResult = await PromptUtils.listPrompt("Set the publicity of the repository: ", [ "private", "internal", "public" ]);
```suggestion
      const publicityResult = await PromptUtils.listPrompt(this, "Set the publicity of the repository: ", [ "private", "internal", "public" ]);
```

2021-03-11 12:56 UTC, veikkahonkanen commented on src/commands/new-repo.ts
> +      const descriptionResult = await PromptUtils.inputPrompt("Give a description for the repository: ");
```suggestion
      const descriptionResult = await PromptUtils.inputPrompt(this, "Give a description for the repository: ");
```

2021-03-11 12:57 UTC, veikkahonkanen requested changes
Use Visitor

2021-03-11 13:02 UTC, veikkahonkanen commented on package-lock.json
> +    },
```suggestion
```

2021-03-11 13:03 UTC, veikkahonkanen commented on package.json
> +    "i": "^0.3.6",
```suggestion
```

2021-03-11 13:09 UTC, veikkahonkanen commented on src/classes/prompt-utils.ts
> +import inquirer from "inquirer";
```suggestion
```

2021-03-11 13:11 UTC, veikkahonkanen commented on src/classes/prompt-utils.ts
> +  static inputPrompt = async (instance: any, message : string) : Promise<string | null> => {
```suggestion
  static inputPrompt = async (instance: any, message: string) : Promise<string | null> => {
```

2021-03-11 13:11 UTC, veikkahonkanen commented on src/classes/prompt-utils.ts
> +  static confirmPrompt = async (instance: any, message : string): Promise<string | null> => {
```suggestion
  static confirmPrompt = async (instance: any, message: string): Promise<string | null> => {
```

2021-03-11 13:12 UTC, veikkahonkanen commented on src/classes/prompt-utils.ts
> +  static listPrompt = async (instance: any, message : string, choices : string[]): Promise<string | null> => {
```suggestion
  static listPrompt = async (instance: any, message: string, choices: string[]): Promise<string | null> => {
```

2021-03-18 11:49 UTC, anttileppa requested changes

2021-03-18 11:49 UTC, anttileppa commented on src/classes/prompt-utils.ts
> +
```suggestion
```

2021-03-18 11:49 UTC, anttileppa commented on src/classes/prompt-utils.ts
> +
```suggestion
```

2021-03-18 11:49 UTC, anttileppa commented on src/classes/prompt-utils.ts
> +
```suggestion
```

2021-03-18 11:49 UTC, anttileppa commented on package.json
> +    "npm": "^7.6.2",
Why do you need npm as a dependecy?

2021-03-19 08:28 UTC, merged