operating system selection added
Metatavu/meta-proj-cli pull request #28
Opened 2021-02-04 08:55 UTC by veikkahonkanen

Resolves #26

2021-02-05 09:26 UTC, jarinykanen requested changes

2021-02-05 09:26 UTC, jarinykanen commented on classes/os-commands.ts
> +}];
```suggestion
const cmds : OsCommand[] = [
  {
    OS : "WINDOWS",
    commands: [
      { name : "copy", command : "copy" }
    ] 
  },
  {
    OS : "LINUX",
    commands: [
      { name : "copy", command : "cp" }
    ] 
  },
  {
    OS : "MAC OS",
    commands: [
      { name : "copy", command : "cp" }
    ] 
  }
];
```

2021-02-05 09:26 UTC, jarinykanen commented on classes/os-commands.ts
> +export class OsCommands {
Add docs

2021-02-05 09:26 UTC, jarinykanen commented on classes/os-utils.ts
> + * searchCmd = provides functionality for getCommand
Move these to function descriptions

2021-02-05 09:26 UTC, jarinykanen commented on classes/os-utils.ts
> + * searchCmd = provides functionality for getCommand
Also add function params and returns

2021-02-05 09:26 UTC, jarinykanen commented on classes/os-utils.ts
> +  };
```suggestion
  static getCommand = async (cmd: string): Promise<string> => {
    try {
      const userConfig: UserConfigJson = await readUserConfig();
      return searchCmd(userConfig.osPref, cmd);
    } catch (err) {
      return Promise.reject(err);
    };
  };
```

2021-02-05 09:26 UTC, jarinykanen commented on classes/os-utils.ts
> +  };
These are not used outside this file --> Move inside static class

2021-02-05 09:26 UTC, jarinykanen commented on classes/os-utils.ts
> +  };
Use this format in other methods as well.

2021-02-05 09:26 UTC, jarinykanen commented on classes/path-utils.ts
> +    os = "LINUX";
Move all OS strings to static enum (include it in the types.ts file)

2021-02-05 09:26 UTC, jarinykanen commented on classes/path-utils.ts
> +function pathFixer(givenPath : string, os? : string) {
Change function name to describe what the function actually does. For example translatePath
Add missing params

2021-02-05 09:26 UTC, jarinykanen commented on classes/path-utils.ts
> +    };
Remove all ; after if statements

2021-02-08 08:07 UTC, anttileppa requested changes

2021-02-08 08:07 UTC, anttileppa commented on classes/path-utils.ts
> +      });
```suggestion
      const activeOs = await OsUtils.getOS();
```

2021-02-08 08:07 UTC, anttileppa commented on classes/path-utils.ts
> +      if(activeOs){
```suggestion
      if (activeOs) {
```

2021-02-08 08:07 UTC, anttileppa commented on classes/os-utils.ts
> +module helperFunctions {
Refactor to private static

2021-02-08 08:07 UTC, anttileppa commented on classes/os-utils.ts
> +    await helperFunctions.readUserConfig().then((userConfig : UserConfigJson) => {
Remove callback syntax

2021-02-08 08:07 UTC, anttileppa commented on classes/os-utils.ts
> +export class OsUtils {
```suggestion
export default class OsUtils {
```

2021-02-08 08:07 UTC, anttileppa commented on commands/select-os.ts
> +    throw(err);
```suggestion
    throw new Error(err);
```

2021-02-08 08:07 UTC, anttileppa commented on classes/path-utils.ts
> +  if ( os === OperatingSystems.WINDOWS) {
```suggestion
  if (os === OperatingSystems.WINDOWS) {
```

2021-02-08 08:52 UTC, eetupur commented on classes/os-commands.ts
> +};
```suggestion
}
```

2021-02-08 08:52 UTC, eetupur commented on classes/os-utils.ts
> + *
```suggestion
```

2021-02-08 08:54 UTC, eetupur commented on classes/os-utils.ts
> +
```suggestion
```

2021-02-08 08:54 UTC, eetupur commented on classes/os-utils.ts
> +  };
```suggestion
    }
  }
```

2021-02-08 08:54 UTC, eetupur commented on classes/os-utils.ts
> +  };
```suggestion
  }
```

2021-02-08 08:55 UTC, eetupur commented on classes/os-utils.ts
> +
```suggestion
```

2021-02-08 08:55 UTC, eetupur commented on classes/os-utils.ts
> +  };
```suggestion
    }
  }
```

2021-02-08 08:56 UTC, eetupur commented on classes/os-utils.ts
> +  };
```suggestion
    }
  }
```

2021-02-08 08:57 UTC, eetupur commented on classes/os-utils.ts
> +      fs.writeFile("./user-config.json", data, "utf8", (err) => {
Couldn't this be done without callback? For example await.

2021-02-08 08:58 UTC, eetupur commented on classes/os-utils.ts
> +
```suggestion
```

2021-02-08 08:58 UTC, eetupur commented on classes/os-utils.ts
> +  };
```suggestion
    }
  }
```

2021-02-08 08:59 UTC, eetupur commented on classes/os-utils.ts
> +   * Searches the corresponding command for the corresponding OS
Not  "...from the correspondin OS"?

2021-02-08 09:00 UTC, eetupur commented on classes/path-utils.ts
> +
```suggestion
```

2021-02-08 09:01 UTC, eetupur commented on classes/path-utils.ts
> +
```suggestion
```

2021-02-08 09:01 UTC, eetupur commented on classes/path-utils.ts
> +};
```suggestion
    }
  }
}
```

2021-02-08 09:01 UTC, eetupur commented on classes/path-utils.ts
> +    };
```suggestion
    }
```

2021-02-08 09:02 UTC, eetupur commented on classes/path-utils.ts
> +    };
```suggestion
    }
```

2021-02-08 09:02 UTC, eetupur commented on classes/path-utils.ts
> +      givenPath = path.join(HOME, givenPath.slice(1))
```suggestion
      givenPath = path.join(HOME, givenPath.slice(1));
```

2021-02-08 09:02 UTC, eetupur commented on classes/path-utils.ts
> +    };
```suggestion
    }
```

2021-02-08 09:02 UTC, eetupur commented on classes/path-utils.ts
> +};
```suggestion
}
```

2021-02-08 09:03 UTC, eetupur commented on commands/new-repo.ts
> +    OsUtils.getCommand("copy").then((command : string) => {
Can this not be done with await and not .then?

2021-02-08 09:04 UTC, eetupur commented on commands/pull-proj.ts
> +    execSync(`${copy} project-config.json ${folderPath}`, {cwd : `.${path.sep}resources`})
```suggestion
    execSync(`${copy} project-config.json ${folderPath}`, {cwd : `.${path.sep}resources`});
```

2021-02-08 09:05 UTC, eetupur commented on commands/new-repo.ts
> +      execSync(`${copy} project-config.json ${folderPath}`, {cwd : `.${path.sep}resources`})
```suggestion
      execSync(`${copy} project-config.json ${folderPath}`, {cwd : `.${path.sep}resources`});
```

2021-02-08 09:06 UTC, eetupur commented on commands/select-os.ts
> +
```suggestion
```

2021-02-08 09:10 UTC, eetupur reviewed
A lot of ; at ends of functions, ifs and elses, don't think they are necessary.

2021-02-08 10:23 UTC, veikkahonkanen commented on commands/new-repo.ts
> +    OsUtils.getCommand("copy").then((command : string) => {
Replaced with await

2021-02-08 10:23 UTC, veikkahonkanen commented on classes/os-utils.ts
> +      fs.writeFile("./user-config.json", data, "utf8", (err) => {
No. https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback

2021-02-08 16:29 UTC, anttileppa requested changes

2021-02-08 16:29 UTC, anttileppa commented on classes/os-utils.ts
> +    try{
```suggestion
    try {
```

2021-02-08 16:29 UTC, anttileppa commented on classes/os-utils.ts
> +  static setOS = async (os : string) => {
```suggestion
  public static setOS = async (os : string) => {
```

2021-02-08 16:29 UTC, anttileppa commented on classes/os-utils.ts
> +  static getOS = async () : Promise<string> => {
```suggestion
  public static getOS = async () : Promise<string | null> => {
```

2021-02-08 16:29 UTC, anttileppa commented on classes/os-utils.ts
> +      }
```suggestion
    try {
      const os : UserConfigJson = await OsUtils.readUserConfig();
      return os?.osPref || null; 
```

2021-02-08 16:29 UTC, anttileppa commented on classes/os-utils.ts
> +        if(err){
```suggestion
        if (err) {
```

2021-02-08 16:29 UTC, anttileppa commented on classes/os-utils.ts
> +    let data = JSON.stringify(userConfig, null, 2);
```suggestion
    const data = JSON.stringify(userConfig, null, 2);
```

2021-02-08 16:29 UTC, anttileppa commented on classes/os-utils.ts
> +    }
```suggestion
    try {
      const data = fs.readFileSync("./user-config.json", "utf8");
      return JSON.parse(data.toString());
    } catch(err) {
      throw new Error ("User config not found: " + err);
    }
```

2021-02-08 16:29 UTC, anttileppa commented on classes/os-utils.ts
> +  private static searchCmd (os : string, command : string) {
```suggestion
  private static searchCmd (os: string, command: string) {
```

2021-02-08 16:29 UTC, anttileppa commented on classes/os-utils.ts
> +  private static searchCmd (os : string, command : string) {
Add returns docs

2021-02-08 16:29 UTC, anttileppa commented on classes/os-utils.ts
> +    }
```suggestion
    return OsCommands.getCmds()
      .filter(item => item.OS == os)
      .flatMap(item => item.commands)
      .find(item => item.name === command);
```

2021-02-08 16:29 UTC, anttileppa commented on classes/path-utils.ts
> +      }
```suggestion
      givenPath = activeOs ? translatePath(givenPath, activeOs) : translatePath(givenPath;
```

2021-02-08 16:29 UTC, anttileppa commented on commands/new-repo.ts
> +    try{
```suggestion
    try {
```

2021-02-09 07:54 UTC, eetupur commented on classes/os-utils.ts
> +      const command : CommandObj = OsUtils.searchCmd(userConfig.osPref, cmd)
```suggestion
      const command : CommandObj = OsUtils.searchCmd(userConfig.osPref, cmd);
```

2021-02-09 07:59 UTC, eetupur commented on commands/select-os.ts
> +    const nameResult = await this.prompt({
```suggestion
    const osResult = await this.prompt({
```

2021-02-09 08:00 UTC, eetupur reviewed
Found a few things that could be improved

2021-02-09 10:06 UTC, anttileppa requested changes

2021-02-09 10:06 UTC, anttileppa commented on classes/os-utils.ts
> +      const command : CommandObj = OsUtils.searchCmd(userConfig.osPref, cmd)
```suggestion
      const command : CommandObj = OsUtils.searchCmd(userConfig.osPref, cmd);
```

2021-02-09 10:13 UTC, anttileppa requested changes

2021-02-09 10:13 UTC, anttileppa commented on commands/new-repo.ts
> +
```suggestion
```

2021-02-09 10:13 UTC, anttileppa commented on commands/new-repo.ts
> +      const copy : string = await OsUtils.getCommand("copy");
```suggestion
    const copy : string = await OsUtils.getCommand("copy");
    try {
```

2021-02-09 10:13 UTC, anttileppa commented on classes/path-utils.ts
> +function translatePath(givenPath : string, os? : string) {
Move to private static

2021-02-09 10:13 UTC, anttileppa commented on classes/path-utils.ts
>  export class PathUtils {
Add visibitities

2021-02-09 10:13 UTC, anttileppa commented on classes/path-utils.ts
> +  static savePath : string = translatePath(defaultSavePath);
change to getter

2021-02-09 10:13 UTC, anttileppa commented on classes/path-utils.ts
> +  static projectPath : string = translatePath(defaultProjectPath);
change to getter

2021-02-09 10:50 UTC, merged