implemented user-config-utils, and attached it to relevant files
Metatavu/meta-proj-cli pull request #55
Opened 2021-02-10 10:53 UTC by eetupur

resolves #46

2021-02-10 11:16 UTC, veikkahonkanen approved these changes

2021-02-10 18:04 UTC, anttileppa requested changes

2021-02-10 18:04 UTC, anttileppa commented on src/classes/os-utils.ts
> +import { userConfigUtils } from "./user-config-utils";
Class names should be captitalized

```suggestion
import { UserConfigUtils } from "./user-config-utils";
```

2021-02-10 18:04 UTC, anttileppa commented on src/classes/os-utils.ts
> +      const userConfig: UserConfigJson = await userConfigUtils.readUserConfig();
Class names should be captitalized
```suggestion
      const userConfig: UserConfigJson = await UserConfigUtils.readUserConfig();
```

2021-02-10 18:04 UTC, anttileppa commented on src/classes/os-utils.ts
> +      const os : UserConfigJson = await userConfigUtils.readUserConfig();
Class names should be captitalized
```suggestion
      const os : UserConfigJson = await UserConfigUtils.readUserConfig();
```

2021-02-10 18:04 UTC, anttileppa commented on src/classes/os-utils.ts
> +    const userConfig : UserConfigJson = await userConfigUtils.readUserConfig();
Class names should be captitalized
```suggestion
    const userConfig : UserConfigJson = await UserConfigUtils.readUserConfig();
```

2021-02-10 18:04 UTC, anttileppa commented on src/classes/os-utils.ts
> +    await userConfigUtils.writeUserConfig(data);
Class names should be captitalized
```suggestion
    await UserConfigUtils.writeUserConfig(data);
```

2021-02-10 18:04 UTC, anttileppa commented on src/classes/user-config-utils.ts
> +export class userConfigUtils {
Class names should be captitalized
```suggestion
export class UserConfigUtils {
```

2021-02-10 18:04 UTC, anttileppa commented on src/classes/user-config-utils.ts
> +export class userConfigUtils {
Add tsconfig

2021-02-10 18:04 UTC, anttileppa commented on src/classes/user-config-utils.ts
> +    static async readUserConfig() : Promise<UserConfigJson> {
```suggestion
  static async readUserConfig() : Promise<UserConfigJson> {
```

2021-02-11 07:53 UTC, anttileppa commented
Tests are not passing

2021-02-11 08:02 UTC, veikkahonkanen approved these changes

2021-02-11 12:24 UTC, veikkahonkanen commented on test/user-config-utils.spec.ts
> +}
remove mockUserConfig

2021-02-11 12:25 UTC, veikkahonkanen commented on test/user-config-utils.spec.ts
> +  UserConfigUtils.writeUserConfig = jest.fn();
Add mockUserConfig to line 15 (not used outside of this function)

2021-02-12 09:03 UTC, veikkahonkanen commented on src/classes/os-utils.ts
>  import fs from "fs";
Reamove fs if not used (Sonar doesn't seem to approve of it either)

2021-02-12 10:15 UTC, veikkahonkanen approved these changes

2021-02-12 11:43 UTC, veikkahonkanen approved these changes

2021-02-16 06:50 UTC, jarinykanen requested changes

2021-02-16 06:50 UTC, jarinykanen commented on src/classes/os-utils.ts
>  import { windows, linux, macos } from 'platform-detect';
```suggestion
import { windows, linux, macos } from "platform-detect";
```

2021-02-16 06:50 UTC, jarinykanen commented on src/classes/os-utils.ts
> +
```suggestion
```

2021-02-16 06:50 UTC, jarinykanen commented on src/classes/os-utils.ts
```suggestion
```

2021-02-16 06:50 UTC, jarinykanen commented on src/classes/user-config-utils.ts
> + * @function checkUserConfig checks that user-config.json exists and creates it, if it doesn't
Move function descriptions out from class docs and to the functions themselves.

2021-02-16 06:50 UTC, jarinykanen commented on src/classes/user-config-utils.ts
> +  static async readUserConfig() : Promise<UserConfigJson> {
```suggestion
  static async readUserConfig(): Promise<UserConfigJson> {
```

2021-02-16 06:50 UTC, jarinykanen commented on src/classes/user-config-utils.ts
> +  static async writeUserConfig(data : string) : Promise<void> {
```suggestion
  static async writeUserConfig(data : string): Promise<void> {
```

2021-02-16 07:26 UTC, veikkahonkanen reviewed
Apparently you pulled 79 to 55.

2021-02-16 11:18 UTC, veikkahonkanen approved these changes

2021-02-17 07:24 UTC, jarinykanen approved these changes

2021-02-17 07:24 UTC, jarinykanen commented on src/classes/user-config-utils.ts
> +   * runs a check after which it reads and returns the contents of user-config.json
```suggestion
   * Runs a check after which it reads and returns the contents of user-config.json
```

2021-02-17 07:24 UTC, jarinykanen commented on src/classes/user-config-utils.ts
> +   * takes the edited version of the contents of user-config.json and writes them after a check
```suggestion
   * Takes the edited version of the contents of user-config.json and writes them after a check
```

2021-02-17 07:24 UTC, jarinykanen commented on src/classes/user-config-utils.ts
> +  static async writeUserConfig(data : string): Promise<void> {
```suggestion
  static async writeUserConfig(data: string): Promise<void> {
```

2021-02-17 07:24 UTC, jarinykanen commented on src/classes/user-config-utils.ts
> +   * checks that user-config.json exists and if it doesn't, creates it
```suggestion
   * Checks that user-config.json exists and if it doesn't, creates it
```

2021-02-17 07:24 UTC, jarinykanen commented on src/classes/user-config-utils.ts
> +  private static async checkUserConfig() : Promise<void> {
```suggestion
  private static async checkUserConfig(): Promise<void> {
```

2021-02-17 07:24 UTC, jarinykanen commented on test/user-config-utils.spec.ts
> +  const data : UserConfigJson = await UserConfigUtils.readUserConfig();
```suggestion
  const data: UserConfigJson = await UserConfigUtils.readUserConfig();
```

2021-02-17 07:27 UTC, merged