added proj-config-utils and its proof of concept functionality to new-repo
Metatavu/meta-proj-cli pull request #65
Opened 2021-02-11 08:47 UTC by eetupur

resolves #57

2021-02-11 09:24 UTC, veikkahonkanen approved these changes

2021-02-12 09:10 UTC, veikkahonkanen approved these changes

2021-02-16 07:09 UTC, jarinykanen requested changes

2021-02-16 07:09 UTC, jarinykanen commented on src/classes/proj-config-utils.ts
> +    static async readProjConfig(outerFolder : string) : Promise<ProjConfigJson> {
```suggestion
    static async readProjConfig(outerFolder: string): Promise<ProjConfigJson> {
```

2021-02-16 07:09 UTC, jarinykanen commented on src/classes/proj-config-utils.ts
> +export class ProjConfigUtils {
Add tsdocs

2021-02-16 07:09 UTC, jarinykanen commented on src/classes/proj-config-utils.ts
> +  static async writeProjConfig(outerFolder : string, data : string) : Promise<void> {
```suggestion
  static async writeProjConfig(outerFolder: string, data: string): Promise<void> {
```

2021-02-16 07:09 UTC, jarinykanen commented on src/classes/proj-config-utils.ts
> +   *
```suggestion
```

2021-02-16 07:09 UTC, jarinykanen commented on src/classes/proj-config-utils.ts
> +   * creates project-config.json from template to given folder
```suggestion
   * Creates project-config.json from template to given folder
```

2021-02-16 07:09 UTC, jarinykanen commented on src/classes/proj-config-utils.ts
> +  static async createProjConfig(outerFolder : string) : Promise<void> {
```suggestion
  static async createProjConfig(outerFolder: string): Promise<void> {
```

2021-02-16 07:09 UTC, jarinykanen commented on src/classes/proj-config-utils.ts
> +  private static async checkProjConfig(outerFolder : string) : Promise<void> {
```suggestion
  private static async checkProjConfig(outerFolder: string): Promise<void> {
```

2021-02-16 07:09 UTC, jarinykanen commented on src/classes/proj-config-utils.ts
> +   * gives the path to project-config.json inside a project folder
```suggestion
   * Gives the path to project-config.json inside a project folder
```

2021-02-16 07:09 UTC, jarinykanen commented on src/classes/proj-config-utils.ts
> +  private static outerToFile(outerFolder : string) : string {
```suggestion
  private static outerToFile(outerFolder: string): string {
```

2021-02-16 07:09 UTC, jarinykanen commented on src/commands/new-repo.ts
>      const copy : string = await OsUtils.getCommand("copy");
```suggestion
    const copy: string = await OsUtils.getCommand("copy");
```

2021-02-16 07:09 UTC, jarinykanen commented on src/interfaces/types.ts
> +export interface ProjConfigJson {
Add docs

2021-02-16 11:21 UTC, veikkahonkanen approved these changes

2021-02-17 07:26 UTC, jarinykanen submitted a review, later dismissed

2021-02-17 07:26 UTC, jarinykanen commented on src/interfaces/types.ts
> +  projectName : string
```suggestion
  projectName: string
```

2021-02-17 07:31 UTC, jarinykanen requested changes

2021-02-17 07:31 UTC, jarinykanen commented on src/classes/proj-config-utils.ts
> +   *
```suggestion
```

2021-02-17 08:40 UTC, veikkahonkanen commented on src/commands/new-repo.ts
>        execSync(`git push -q origin develop`, {cwd : repoPath});
spawnSync("git branch -m master develop", {cwd : repoPath});
    finishRepo(repoPath);
  } else {
    const copy : string = await OsUtils.getCommand("copy");
    const copy: string = await OsUtils.getCommand("copy");
    try {
      spawnSync("git init", {cwd : repoPath});
      spawnSync(`${copy} project-config.json ${folderPath}`, {cwd : `.${path.sep}resources`});
      spawnSync(`${copy} project-config-template.json ${folderPath}${path.sep}project-config.json`, {cwd : `.${path.sep}resources`});
      spawnSync("git checkout -q -b develop", {cwd : repoPath});
      spawnSync(`${copy} README.md ${repoPath}`, {cwd : `.${path.sep}resources`});
      spawnSync(`git add README.md`, {cwd : repoPath});
      spawnSync(`git commit -q -m "first commit"`, {cwd : repoPath});
      spawnSync(`git push -q origin develop`, {cwd : repoPath});

2021-02-23 08:23 UTC, veikkahonkanen commented on src/classes/proj-config-utils.ts
> +  }
Probably a job for path-utils instead

2021-02-23 08:24 UTC, veikkahonkanen approved these changes

2021-02-23 17:39 UTC, jarinykanen approved these changes

2021-02-23 17:39 UTC, merged