Added installation utilities
Metatavu/meta-proj-cli pull request #73
Opened 2021-02-12 07:31 UTC by veikkahonkanen

Resolves #72

2021-02-12 09:07 UTC, eetupur commented on src/classes/install-sw-refs.ts
> +        }
could use a shorter syntax on many of these
```suggestion
       return (installUtil === "brew") ? "node" : "nodejs";
```

2021-02-12 09:08 UTC, eetupur commented on src/classes/install-sw-refs.ts
> +        if (installUtil == "sudo apt") {
same here

2021-02-12 09:08 UTC, eetupur commented on src/classes/install-sw-refs.ts
> +        }
same here

2021-02-12 09:08 UTC, eetupur commented on src/classes/install-sw-refs.ts
> +        }
same here

2021-02-12 09:16 UTC, eetupur commented on src/classes/install-utils.ts
> +      }
same here

2021-02-12 09:17 UTC, eetupur commented on src/classes/install-utils.ts
> +      }
same here

2021-02-12 09:18 UTC, eetupur reviewed
found cases where better syntax could be used

2021-02-12 10:14 UTC, eetupur approved these changes

2021-02-15 11:25 UTC, eetupur approved these changes

2021-02-16 07:22 UTC, jarinykanen requested changes

2021-02-16 07:22 UTC, jarinykanen commented on src/classes/install-sw-refs.ts
> +export class InstallSwRefs {
Add tsdocs

2021-02-16 07:22 UTC, jarinykanen commented on src/classes/install-sw-refs.ts
> +  public static async getInstallRef(installUtil : string, software : string) : Promise<string> {
```suggestion
  public static async getInstallRef(installUtil: string, software: string): Promise<string> {
```

2021-02-16 07:22 UTC, jarinykanen commented on src/classes/install-sw-refs.ts
> +  public static async getInstallRef(installUtil : string, software : string) : Promise<string> {
Add also missing tsdocs

2021-02-16 07:22 UTC, jarinykanen commented on src/classes/install-sw-refs.ts
> +  public static async getBashRef(software : string) : Promise<string> {
```suggestion
  public static async getBashRef(software: string): Promise<string> {
```

2021-02-16 07:22 UTC, jarinykanen commented on src/classes/install-utils.ts
> +export class InstallUtils {
Add docs

2021-02-16 07:22 UTC, jarinykanen commented on src/classes/install-utils.ts
> +  public static async installBrew() : Promise<string> {
```suggestion
  public static async installBrew(): Promise<string> {
```

2021-02-16 07:22 UTC, jarinykanen commented on src/classes/install-utils.ts
> +    if (os == OperatingSystems.MAC){
```suggestion
    const os : string = await OsUtils.getOS();

    if (os == OperatingSystems.MAC){
```

2021-02-16 07:22 UTC, jarinykanen commented on src/classes/install-utils.ts
> +  public static async installSW(software : string) : Promise<string> {
```suggestion
  public static async installSW(software: string): Promise<string> {
```

2021-02-16 07:22 UTC, jarinykanen commented on src/classes/install-utils.ts
> +  }
```suggestion
  public static async isInstalled(software: string): Promise<boolean> {
    const bashRef = await InstallSwRefs.getBashRef(software);

    if(bashRef == "brew"){
      try {
        const str = `which ${bashRef}`;
        const result = execSync(str).toString();
        return (result.search(/not found/) == -1);
      } catch (err) {
        throw new Error(`Error when checking software ${bashRef}: ${err}`);
      }

    } else {
      try {
        const str = `${bashRef} --version`;
        const result = execSync(str).toString();
        return (result.search(/is not recognized/) == -1);
      } catch (err) {
        throw new Error(`Error when checking software ${bashRef}: ${err}`);
      }
    }
  }
```

2021-02-16 07:22 UTC, jarinykanen commented on src/interfaces/types.ts
> +export enum Software {
Add tsdocs

2021-02-16 08:15 UTC, veikkahonkanen commented on src/classes/install-sw-refs.ts
> +export class InstallSwRefs {
added tsdocs

2021-02-16 08:17 UTC, veikkahonkanen commented on src/classes/install-sw-refs.ts
> +  public static async getInstallRef(installUtil : string, software : string) : Promise<string> {
reformatted line 12, added tsdocs

2021-02-16 08:19 UTC, veikkahonkanen commented on src/classes/install-utils.ts
> +export class InstallUtils {
added docs

2021-02-16 08:24 UTC, veikkahonkanen commented on src/interfaces/types.ts
> +export enum Software {
added tsdocs

2021-02-16 08:33 UTC, eetupur commented on src/classes/install-utils.ts
> +
```suggestion
```

2021-02-16 08:33 UTC, eetupur commented on src/classes/install-utils.ts
> +
```suggestion
```

2021-02-16 08:34 UTC, eetupur requested changes
found unnecessary lines

2021-02-17 07:35 UTC, jarinykanen requested changes

2021-02-17 07:35 UTC, jarinykanen commented on src/classes/install-sw-refs.ts
> +  public static async getInstallRef(installUtil: string, software: string): Promise<string> {
```suggestion
  /**
   * Get Install Reference for Installation Utils class
   * 
   * @param installUtil is the installation utility which needs its corresponding command
   * @param software is the software in question
   * @returns installation reference used in bash to install the software
   */
  public static async getInstallRef(installUtil: string, software: string): Promise<string> {
```

2021-02-17 07:35 UTC, jarinykanen commented on src/classes/install-sw-refs.ts
> +   */
```suggestion
   * Get bash references for Installation Utils class
   * 
   * @param software is the software in question
   * @returns bash reference for the software
   */
```

2021-02-17 07:35 UTC, jarinykanen commented on src/classes/install-utils.ts
> +    const os : string = await OsUtils.getOS();
```suggestion
    const os: string = await OsUtils.getOS();
```

2021-02-17 07:35 UTC, jarinykanen commented on src/classes/install-utils.ts
> +  }
```suggestion
  /**
   * Install software command for bash
   * 
   * @param software is the desired software to be installed
   * @returns software installation command that is run by the wizard
   */
  public static async installSW(software: string): Promise<string> {
    const installUtil: string = await OsUtils.getCommand(CommandNames.installUtil);
    const installRef: string = await InstallSwRefs.getInstallRef(installUtil, software);

    return `${installUtil} install ${installRef}`;
  }
```

2021-02-17 07:35 UTC, jarinykanen commented on src/classes/install-utils.ts
> +  public static async isInstalled(software : string) : Promise<boolean> {
```suggestion
  /**
   * Attempts to confirm a software's installation status
   * 
   * @param software is the software that is being checked
   * @returns a boolean that indicates if a software has already been installed
   */
  public static async isInstalled(software : string) : Promise<boolean> {
```

2021-02-23 08:36 UTC, eetupur approved these changes

2021-02-24 06:06 UTC, jarinykanen requested changes

2021-02-24 06:06 UTC, jarinykanen commented on src/classes/install-utils.ts
> +    const cmds : string[] = [];
```suggestion
    const cmds: string[] = [];
```

2021-02-24 06:06 UTC, jarinykanen commented on src/classes/install-utils.ts
> +    const cmds : string[] = [];
```suggestion
    const cmds: string[] = [];
```

2021-02-24 06:06 UTC, jarinykanen commented on src/classes/install-utils.ts
> +  public static async isInstalled(software : string) : Promise<boolean> {
```suggestion
  public static async isInstalled(software: string): Promise<boolean> {
```

2021-02-24 06:27 UTC, jarinykanen approved these changes

2021-02-24 06:27 UTC, merged