Added Quarkus creation function
Metatavu/meta-proj-cli pull request #81
Opened 2021-02-15 13:12 UTC by veikkahonkanen

Resolves #80

2021-02-15 13:53 UTC, eetupur commented on src/commands/new-proj/create-quarkus.ts
> +  const orgName = "fi.metatavu";
shouldnt this be in env?

2021-02-15 13:55 UTC, eetupur commented on src/commands/new-proj/create-quarkus.ts
> +  let kotlinS : string = null;
more readable, do same for kotlinS
```suggestion
  let kotlinString : string = null;
```

2021-02-15 13:55 UTC, eetupur requested changes
suggesting better naming

2021-02-15 14:04 UTC, eetupur approved these changes

2021-02-16 07:57 UTC, jarinykanen requested changes

2021-02-16 07:57 UTC, jarinykanen commented on src/commands/new-proj/create-quarkus.ts
> +export const CreateQuarkus = async (projName : string, kotlin : boolean, gradle : boolean) : Promise<string> => {
```suggestion
/**
 * Constructs creation command for Quarkus projects
 *
 * @param projName desired project name
 * @param kotlin true/false if using Kotlin
 * @param gradle true/false if using Gradle
 * 
 * @returns a command that is used to create the Quarkus project
 */
export const CreateQuarkus = async (projName: string, kotlin: boolean, gradle: boolean): Promise<string> => {
```

2021-02-16 07:57 UTC, jarinykanen commented on src/commands/new-proj/create-quarkus.ts
> +  gradle ? gradleString = "\
```suggestion
  const kotlinString: string =  kotlin ? ", kotlin" : "";
  const gradleString: string = gradle ? gradleString = "\
  -DbuildTool=gradle" : "";
```

2021-02-16 08:37 UTC, eetupur approved these changes

2021-02-23 17:43 UTC, jarinykanen approved these changes

2021-02-23 17:43 UTC, merged