Added Create React and Clean React tests
Metatavu/meta-proj-cli pull request #96
Opened 2021-02-23 06:28 UTC by veikkahonkanen

Resolves #94

2021-02-24 05:54 UTC, jarinykanen requested changes

2021-02-24 05:54 UTC, jarinykanen commented on test/create-react.spec.ts
> +
```suggestion
```

2021-02-24 05:54 UTC, jarinykanen commented on test/create-react.spec.ts
> +  const str : string = await CreateReact('test');
```suggestion
  const str: string = await CreateReact('test');
```

2021-02-24 05:54 UTC, jarinykanen commented on test/create-react.spec.ts
> +  const strArr : string[] = await CleanReact('', '');
```suggestion
  const strArr: string[] = await CleanReact('', '');
```

2021-02-24 07:37 UTC, eetupur approved these changes

2021-02-25 08:02 UTC, jarinykanen approved these changes

2021-02-25 08:03 UTC, merged