Added Yaml Utils tests
Metatavu/meta-proj-cli pull request #98
Opened 2021-02-23 07:05 UTC by veikkahonkanen

Resolves #97

2021-02-24 06:03 UTC, jarinykanen requested changes

2021-02-24 06:03 UTC, jarinykanen commented on test/yaml-utils.spec.ts
> +                port:8088};
```suggestion
  const args = {
    name:"test",
    image:'test',
    port:8088
  };
```

2021-02-24 07:37 UTC, eetupur approved these changes

2021-02-25 08:09 UTC, jarinykanen requested changes

2021-02-25 08:09 UTC, jarinykanen commented on test/yaml-utils.spec.ts
> +    image:'test',
```suggestion
    image:"test",
```

2021-02-25 08:09 UTC, jarinykanen commented on test/yaml-utils.spec.ts
> +  await YamlUtils.createYaml(args, 'pod', '');
```suggestion
  await YamlUtils.createYaml(args, "pod", '');
```

2021-02-25 08:09 UTC, jarinykanen commented on test/yaml-utils.spec.ts
> +it('provides create yaml function', async () => {
```suggestion
it("provides create yaml function", async () => {
```

2021-02-25 08:09 UTC, jarinykanen commented on test/yaml-utils.spec.ts
> +it('is able to read a .yaml file', async () => {
```suggestion
it("is able to read a .yaml file", async () => {
```

2021-02-25 08:09 UTC, jarinykanen commented on test/yaml-utils.spec.ts
> +  await YamlUtils.printYaml('keycloak', './resources');
```suggestion
  await YamlUtils.printYaml("keycloak", "./resources");
```

2021-02-25 08:09 UTC, jarinykanen commented on test/yaml-utils.spec.ts
> +it('provides a delete yaml command string', async () => {
```suggestion
it("provides a delete yaml command string", async () => {
```

2021-02-25 08:09 UTC, jarinykanen commented on test/yaml-utils.spec.ts
> +  const str = await YamlUtils.deleteYaml('deployment', '');
```suggestion
  const str = await YamlUtils.deleteYaml("deployment", "");
```

2021-02-25 08:28 UTC, eetupur approved these changes

2021-02-25 11:25 UTC, jarinykanen approved these changes

2021-02-25 11:25 UTC, jarinykanen commented on test/yaml-utils.spec.ts
> +    port:8088
```suggestion
    name: "test",
    image: "test",
    port: 8088
```

2021-02-25 11:25 UTC, merged